### ISSUE TITLE
git ignore 관련

### ISSUE THREAD

**Issue by jinhyeok-kim** [seong954t/Algorithm#8]
.iml과 .xml 관련해서 ignore 처리가 제대로 되어있지 않은 것 같습니다.

.iml은 되어있지 않고
.xml은 
nosetests.xml
coverage.xml

이 두가지 경우에 대해서만 ignore 처리가 되어있는 것으로 보입니다.

**Comment by jinhyeok-kim** [comment]
.idea 디렉터리 관련 ignore도 필요 할 것으로 보입니다.

**Comment by jinhyeok-kim** [comment]
수정해서 pullrequest 올려뒀습니다.

**Comment by seong954t** [comment]
#10 PR 확인 후 Merge 진행하였습니다.
해당 issue Close하겠습니다.
감사합니다.
